# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localitat', models.CharField(max_length=200)),
                ('adressa', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=b'')),
                ('preu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NotaCalendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateField', models.DateField(auto_now_add=True)),
                ('nota', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognoms', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('btc_address', models.CharField(max_length=34, null=True)),
                ('id_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cases')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Xat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notacalendario',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Persona'),
        ),
        migrations.AddField(
            model_name='factura',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Persona'),
        ),
    ]
